apiVersion: v2
name: gymglow
description: A Helm chart for GymGlow application. Supports multiple installations on the same cluster by using dynamic release names.
type: application
version: 0.1.11
appVersion: "1.1"
