# Nginx configuration for serving the frontend application
server {
    # tells Nginx to listen for http requests on port 80
    listen 80;
    
    # tells nginx where to find the files to serve
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Error pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
