apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gymglow.fullname" . }}-config
  labels:
    {{- include "gymglow.labels" . | nindent 4 }}
data:
  POSTGRES_USER: "user"
  POSTGRES_DB: "gymglow"
  POSTGRES_HOST: {{ include "gymglow.fullname" . }}-{{ .Values.names.mariadbService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gymglow.fullname" . }}-secret
  labels:
    {{- include "gymglow.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  USER: {{ .Values.appUser | b64enc | quote }}
