apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gymglow.fullname" . }}-backend
  labels:
    {{- include "gymglow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gymglow.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "gymglow.fullname" . }}-backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gymglow.fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gymglow.fullname" . }}-config
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gymglow.fullname" . }}-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gymglow.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "gymglow.fullname" . }}-secret
                  key: USER
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z {{ include "gymglow.fullname" . }}-{{ .Values.names.mariadbService }} 5432; do echo waiting for db; sleep 2; done']
