apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  template:
    spec:
      containers:
      - name: db
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - user
            - -d
            - gymglow
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - user
            - -d
            - gymglow
          initialDelaySeconds: 5
          periodSeconds: 10
